### ISSUE TITLE
Switch to `github.com/sigstore/cosign/v2`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/release-sdk#177]
We should update our implementation to work with the cosign `v2` module, which is a breaking change compared to `v1`.

**Comment by saschagrunert** [comment]
cc @kubernetes-sigs/release-engineering

**Comment by cpanato** [comment]
I will do that
/assign

**Comment by saschagrunert** [comment]
Awesome, thank you @cpanato !

**Comment by sohankunkerkar** [comment]
Hey @cpanato. do you have any updates on this?

**Comment by cpanato** [comment]
@sohankunkerkar I will try to get back to this week, i was sick and out and last week was kubecon
