### ISSUE TITLE
Implement container image signing

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/release-sdk#21]
This issue tracks the implementation part of https://github.com/kubernetes/release/issues/2383

Goal is to add the container image signing logic to the `sign` package: 
https://github.com/kubernetes-sigs/release-sdk/blob/fc5cf4a16dfd3e2753a54319e77421aef33c22ad/sign/sign.go#L69

Unit tests have to be written as well.

**Comment by cpanato** [comment]
i will work on this
/assing
/remove-help

**Comment by cpanato** [comment]
/assign

need to first fix typos lol
