### ISSUE TITLE
Implement image signing verification

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/release-sdk#23]
This issue tracks the implementation part of https://github.com/kubernetes/release/issues/2383

Goal is to add the signature verification logic for **container images** to the `sign` package: 
https://github.com/kubernetes-sigs/release-sdk/blob/fc5cf4a16dfd3e2753a54319e77421aef33c22ad/sign/sign.go#L98

Unit tests have to be written as well.

**Comment by PushkarJ** [comment]
/assign

Happy to work on this. 

/sig security

**Comment by PushkarJ** [comment]
Asked a couple of questions on slack about this: https://kubernetes.slack.com/archives/C2C40FMNF/p1644269088802199

(Sharing for folks who are maybe watching this issue but not slack)
