### ISSUE TITLE
Implement file signing verification

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/release-sdk#30]
This issue tracks the implementation part of https://github.com/kubernetes/release/issues/2383

Goal is to add the signature verification logic for **files** to the `sign` package: 
https://github.com/kubernetes-sigs/release-sdk/blob/fc5cf4a16dfd3e2753a54319e77421aef33c22ad/sign/sign.go#L98

Unit tests have to be written as well.

**Comment by matglas** [comment]
Update: The implementation is far but the integration tests are stuck on a part I am not able yet to find a solution for. I'm trying to investigate but any insight or help is welcome on PR #68
