### ISSUE TITLE
Populate the SignedObject with the information about signed image/artifact

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/release-sdk#37]
The `SignedObject` object returned when signing and verifying images/artifacts signed with the `sign` package is currently empty. We should put some information about the signed artifact in that object, so consumers can use it for validation or exposing that information to users.

We can include information such as:

* SHA/digest of the signed image/artifact
* Link to the signature (`.sig`) file

Eventually, we might want to include other information as needed.

**Comment by saschagrunert** [comment]
@xmudrii do you already had a chance to start working on this? :)

**Comment by xmudrii** [comment]
@saschagrunert I'll try to work on it this week.

**Comment by xmudrii** [comment]
I'm currently super busy with the university, so I'll unassign myself and someone else can take over.
/unassign

**Comment by saschagrunert** [comment]
@cpanato do you wanna take this or should I take care of it?

**Comment by cpanato** [comment]
@saschagrunert I can work on that

/assign

**Comment by cpanato** [comment]
@xmudrii no worries!
