### ISSUE TITLE
libraries under MPL from hashicorp

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/release-sdk#56]
please see https://github.com/sigstore/sigstore/issues/384 for context

How do we approach this problem?

**Comment by saschagrunert** [comment]
We should collect a list of affected projects as well as the dependency tree (go mod why) to get their origin. Then we can work around this limitation.

**Comment by dims** [comment]
@saschagrunert do we want to do this in 1.25?

**Comment by saschagrunert** [comment]
@dims yes we can! Looks like that updating cosign to 1.8.x should already do the trick accordingly to https://github.com/sigstore/sigstore/issues/384#issuecomment-1114266058, right?

**Comment by dims** [comment]
yes, i think so!

**Comment by saschagrunert** [comment]
Cool, closing this one for now.
