### ISSUE TITLE
Implement e2e tests for file signing

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/release-sdk#93]
We recently added a GitHub action job to e2e test the image signing: https://github.com/kubernetes-sigs/release-sdk/blob/main/test/e2e/sign_test.go

Goal is to do the same for file signatures.

@kubernetes-sigs/release-engineering I think this is a good first issue to get in touch with the code base. Is there anyone who want to work on this?

Part of https://github.com/kubernetes/enhancements/issues/3031

**Comment by pradeepnnv** [comment]
I would like to try this out.

**Comment by ShivangShandilya** [comment]
I would like to take a look if no one is currently working on this

**Comment by xmudrii** [comment]
@ShivangShandilya As far as I know, there's no progress on this issue. You can give it a try if you're interested!
